[package]
name = 'mdl'
publish = false
version = '0.1.0'
edition = '2021'

[lib]
crate-type = ['staticlib']
name = 'mdl'

[dev-dependencies]
extendr-engine = { version = "0.7.1" }

[dependencies]
extendr-api = { version = "0.7.1" }